### ISSUE TITLE
"No such file or directory" (OSError #2) on Win10 Linux Subsystem

### ISSUE THREAD

**Issue by dylanh724** [discordapp/discord-rpc#149]
The way to build on Windows is a bit tedious without using bash. Unfortunately, it seems like it won't build using this since it's trying to detect what system I'm on (technically on Win, but not Linux -- probably confused the script).

I'm not really sure how my OS would look when checking -- but somehow we need to check for this. Otherwise RIP installing python, pip, and building on a Windows machine~

**Comment by msciotti** [comment]
Hey Dylan. There's no need for bash on Windows for the install script to work. You should just be able to run `python build.py unity` from the root directory of the repository, and it'll roll the right DLLs for a unity project. If you're doing something like running under Window's ubuntu subsystem...yeah, we probably aren't checking for that. In which case, you should just grab the latest release like you mentioned in https://github.com/discordapp/discord-rpc/issues/150.

**Comment by dylanh724** [comment]
I forgot to follow-up -- even normal Windows cmd is still getting an error (although a different one - file not found). I can't seem to get it working.  Here is the latest straight from cmd:

```shell
> python build.py unity
Making builds
Making C:\UnityProjects\Discord\discord-rpc-src-3.0.0\builds\win32-dynamic
Making C:\UnityProjects\Discord\discord-rpc-src-3.0.0\builds\install\win32-dynamic
--- Building win32-dynamic
Traceback (most recent call last):
  File "build.py", line 313, in <module>
    sys.exit(cli())
  File "C:\Python36\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python36\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Python36\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python36\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python36\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Python36\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "build.py", line 79, in unity
    just_release=True
  File "C:\Python36\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "build.py", line 297, in libs
    build_lib('win32-dynamic', generator32, dynamic_options, just_release)
  File "build.py", line 194, in build_lib
    subprocess.check_call(initial_cmake)
  File "C:\Python36\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I tried this on both my laptop and desktop, resulting in the same err.

**Comment by dylanh724** [comment]
Well! lol.

![image](https://user-images.githubusercontent.com/8840024/37899972-7e28d972-311f-11e8-9058-386fad8ad4d3.png)

I thought this was included with Python, oops. For Windows users, should probably add this to the readme

**Comment by msciotti** [comment]
Sure, I can add a note to the readme.
