### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by wolfy01** [discordapp/discord-rpc#299]
> SimplePresence@2.7.0 custom /home/wolfy3543/simplep/SimplePresence
> electron scripts/custom/main.js

App threw an error during load
/home/wolfy3543/simplep/SimplePresence/node_modules/discord-rpc/src/client.js:634
        ...r,
        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/wolfy3543/simplep/SimplePresence/node_modules/discord-rpc/src/index.js:6:11)
A JavaScript error occurred in the main process
Uncaught Exception:
/home/wolfy3543/simplep/SimplePresence/node_modules/discord-rpc/src/client.js:634
        ...r,
        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/wolfy3543/simplep/SimplePresence/node_modules/discord-rpc/src/index.js:6:11)

**Comment by wolfy01** [comment]
This is when I try to use: https://github.com/justJS/SimplePresence/
What I followed: https://github.com/justJS/SimplePresence/wiki/Setup

Btw I'm using Linux on a Chromebook :/

**Comment by Lachee** [comment]
This is a syntax error, so this has nothing to do with this library. Probbly look in your client.js on line 634 and see what you have written. Its wrong according to the error. If you still cannot figure it out, it might be best to ask the justJS/SimplePresence team instead.

**Comment by wolfy01** [comment]
> This is a syntax error, so this has nothing to do with this library. Probbly look in your client.js on line 634 and see what you have written. Its wrong according to the error. If you still cannot figure it out, it might be best to ask the justJS/SimplePresence team instead.

I haven't changed anything, also, this occurs when installing it via npm and not using justJS/SimplePresence's npm install. However I have found the source in client.js

```
  getRelationships() {
    const types = Object.keys(RelationshipTypes);
    return this.request(RPCCommands.GET_RELATIONSHIPS)
      .then((o) => o.relationships.map((r) => ({
        ...r,
        type: types[r.type],
      })));
  }

**Comment by wolfy01** [comment]
I ended up completely removing  "...r," that seemed to fix it :/

**Comment by msciotti** [comment]
Definitely seems like a question for the folks who implemented `SimplePresence`. The underlying RPC code has not changed at all in quite some time, so this is out of scope for this repo. Best of luck!
