### ISSUE TITLE
NoClassDefFoundError when running minecraft client with discord-rpc

### ISSUE THREAD

**Issue by ItzzParsher** [discordapp/discord-rpc#360]
---- Minecraft Crash Report ----
// You're mean.

Time: 3/5/22, 12:37 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/arikia/dev/drpc/callbacks/ReadyCallback
	at Lucky.Client.<init>(Client.java:10)
	at Lucky.Client.<clinit>(Client.java:5)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:470)
	at net.minecraft.client.Minecraft.run(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(Main.java:113)
	at Start.main(Start.java:11)
Caused by: java.lang.ClassNotFoundException: net.arikia.dev.drpc.callbacks.ReadyCallback
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 6 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at Lucky.Client.<init>(Client.java:10)
	at Lucky.Client.<clinit>(Client.java:5)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:470)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(Main.java:113)
	at Start.main(Start.java:11)

-- System Details --
Details:
	Minecraft Version: 1.8.8
	Operating System: Windows 10 (amd64) version 10.0
	CPU: <unknown>
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 868831744 bytes (828 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 3 total; -XX:+ShowCodeDetailsInExceptionMessages -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: mcp
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: ~~ERROR~~ NullPointerException: Cannot read field "useVbo" because "this.this$0.gameSettings" is null
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: Cannot read field "resourcePacks" because "this.this$0.gameSettings" is null
	Current Language: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.client.resources.LanguageManager.getCurrentLanguage()" because the return value of "net.minecraft.client.Minecraft.access$3(net.minecraft.client.Minecraft)" is null
	Profiler Position: N/A (disabled)
	CPU: <unknown>

**Comment by devsnek** [comment]
I think you want this repo: https://github.com/Vatuu/discord-rpc

**Comment by ghost** [comment]
this isn't an issue with discord rpc, it is an issue with ur eclipse porject setup

**Comment by ghost** [comment]
> I think you want this repo: https://github.com/Vatuu/discord-rpc

he is already using that lol (if u actually read the log)
